services:
  postgres:
    image: postgres:16
    container_name: 'db'
    restart: always
    env_file: db.env
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: 'redis'
    restart: always
    ports:
      - '6379:6379'

volumes:
  pg_data:
